//don't code like a monkey
doWork(function(data) {
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
}, function(error) {
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
}, function(whatever) {
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...  
});

var successFn = function(data) {
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
}

var errorFn = function(err) {
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...  
}

var whateverFn = function(whatever) {
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
  //...code...
}

doWork(successFn, errorFn, whateverFn);

//modularize code and create small cohesive 
//functions that have single responsibilities and
//reuse those functions as arguments as needed.